hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "e0831bf3d079d127c9a36d5e2dd1cb84c13c1c26cbd6f8bb3518ce475c81159e"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "971916846fa6d86fe9986c6f34370b62de5aa9c219e709011851397af8fd6fb5"
metafile = true

[[files]]
file = "mods/advanced-loot-info.pw.toml"
hash = "10a722b3f6aeed78cc5e8010d603d45dc00bd82dda8d01029672ff9765060cad"
metafile = true

[[files]]
file = "mods/altorigingui.pw.toml"
hash = "95d278261dad118bd5ce0474d4f8d05ceab0c81e16159cb94182b550187cd473"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "f7933fc2034c3eb8601f3eddaa75f03d0a3f68dce19ee553aed57d35163cb21a"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "f3f98ccb142504aa558f3250b5a9bcda5d9fb45634562a4b7f886489575f6f5a"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/arrp.pw.toml"
hash = "597e7f2ba83102b2e28a4563c57bdde56f0f77c35cbc8c008a995210f0aacb47"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
hash = "884814a2b4276def6b0a2ae55d748115e5da30fb439889923be2baec8b70dbaa"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "30eff8901d5955ab62196e335926047f6c00278fd95eb04b4e4b7122a8c31f15"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "ab1e22cc66189067e002a204c70c553cc7cc0e738bd602f405d7cc37561260be"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "9e94089231d50ff38c030369b6b9b8af0c8d9f0b495611ae3b29be18656d35bb"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "6d7c5793f88c52421dc11f48b3bf12400e7a451b9297e80fe33b776cc2af2c1d"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "4b8ffbe47270effb2da83ff2fba6e5dea0158a515033b61a484a21aae6146a76"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
hash = "f04f6619202e8b2b22e33c4ce152f879633577d82ada897327603c050da601df"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b304ca940d63b62df1d4c4bc05a90f4429c83c613509dd6521bf276529683fc"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/casualcosmetics-1.0.2.jar"
hash = "f6c19cb7cfa26453ba2f799ec6fb9afb398f0fc4537f7561f5749f45c24c839f"

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "30ad9dfe5d3e7aa49aed43266c6e3bd76187f9126434e1652d44fa00ca29bf5c"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "d226ea199a740bff4e07877a952dc6972273fb92fcddd258a8989bfbede63a8d"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "d47260d085f9c59609bbc7582968e60f4c476d934c815142360bbcc4b5113a4d"
metafile = true

[[files]]
file = "mods/complex-hex.pw.toml"
hash = "7deff0eada2fe367cf5d47b8f48ace87d6af8baa4044b1e1be0491d9088bb866"
metafile = true

[[files]]
file = "mods/consulars-origins.pw.toml"
hash = "98009c9c20188c507a860a4a7a3af61b95a18bf1ca8c8b952f16dca66eb8fd5e"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/cpmsvcc.pw.toml"
hash = "de28e3702a5f987a8c904ad39d86dccf41614a16cb80bf1673ea08e60cfed2c0"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "f76188c6e4714a70ea367d7f7a566b05c935a9f19e23f0352f4eb0271a985376"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "2801e258fc6e9b96900865e1dce5bc9167f01e993b8aad2672b5d671d3524bf8"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "97fa95db99748805bfb5dd844fee528d6fb67c492e6366681ef657bbc7820a5f"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "af83eb1ea0f7a36e4424248c744c1cbebb5045d361e843b873d4d89bf65ad8ad"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "630b6d667264f8f5a580af52952ca9ef031d4f6db81a41e22d78738dcc53b154"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "4463005ad6ae41db2bf707952d6945297f48601a42ec8b6cac8aef09d653ffd2"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
hash = "e4f4f6156fb0156a94ec25a5d7e62f4af1f0c9bed6ba050b505f23d4b5c8bb6f"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "a8aa09f4f156506ed902620637557fb3623084d5d994f7b4f1f01eb4a19916b6"
metafile = true

[[files]]
file = "mods/do-api.pw.toml"
hash = "eb717689205472c2579d8c6900c64183d5feb2b5d6e05063a5ed0202cab9717d"
metafile = true

[[files]]
file = "mods/ducky-periphs.pw.toml"
hash = "cc6eb3c71b6f59304db3600f9a4878526a87af81f4b2d195e3a8a21d513878ee"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "0bcc0df994ebbe98efc2f87c653cd0ae0a81bb0ca47b5adacba0974c5c6406c5"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "b58e81bdab1b3db9bdbf331e45f7438abdf62b63e495dccc003b3ebdf02a3abf"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "b38a80fb1bb72759cebf627d5e160102c6eb2895528d6cb1db096eee092daad2"
metafile = true

[[files]]
file = "mods/enhancedbookwriting.pw.toml"
hash = "1538ea25f00683d7f8034a77e9d1413540a5a9a73832699c6ff06c9d7b6870f8"
metafile = true

[[files]]
file = "mods/enhancedvisuals.pw.toml"
hash = "1c90ca6a70db874423c16937b0b253a9acc31c912031d01d346d98dc4c310637"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "171419759aec842f5defe4237e24be8d6aa7c6e2a26703dc2e9d07e71412dfc4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7eefb0f3d1b793f7dc57ee7cf368d055c9b1bf3556f61179f38f1c49c163c1bd"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "f91ca238ef6d15fa97e284475eb454a17590e87ed4277e8b6462e1dce5924c66"
metafile = true

[[files]]
file = "mods/ephemera.pw.toml"
hash = "442d01ebee947c4383de13fc207425cc73dabbb0dadc6f0e72d232b6ebb7032b"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "b6aaea7b4329e3285c05d8b341aab754d955662072cdfc6b2fc806561941af2e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "1ee56d5feb0ede9397b26f3c5b7543a3556088146d154b55172ef0e8b1a97705"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "fcfd264784dcda039d9efc0b3e47ef1f04521698761a34d2f20379d5f9c0fe26"
metafile = true

[[files]]
file = "mods/ftb-library-fabric.pw.toml"
hash = "7c4c132e1ffb20c72dfc2b9288cffc457df74417b264b83a007f969b323fecff"
metafile = true

[[files]]
file = "mods/ftb-ultimine-fabric.pw.toml"
hash = "448e563f4786e28ce661929ffdd4d16639a06c1a3b025418d50e317207b76a4b"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "3ba1f8150b574b10a258a4af832ed6fa1817b8ec2a2401fe29b303238778c1c6"
metafile = true

[[files]]
file = "mods/hex-casting.pw.toml"
hash = "e7618fe94cbf0b7ea032e45cb448ab8151773ef71adb6dda8becd4d2fcc4dab5"
metafile = true

[[files]]
file = "mods/hex-machina.pw.toml"
hash = "6a0af715b6a087f28f3a440f18b73b87786ef293a475c186659b7b5eac10ffa3"
metafile = true

[[files]]
file = "mods/hexal.pw.toml"
hash = "3e51d9ad93efb292181f8960816a58707ae28841c310b77c28721ac7039931d1"
metafile = true

[[files]]
file = "mods/hexcassettes.pw.toml"
hash = "39e27b12d6b188df2b249bf84ed8427c62a7d9c9802ab0469304d554f89f43be"
metafile = true

[[files]]
file = "mods/hexchanting.pw.toml"
hash = "d62dfc7169dd744c050748104bf0c9e7cc3fb67267f4c12d3c19c2fb48acbac3"
metafile = true

[[files]]
file = "mods/hexdebug.pw.toml"
hash = "b48832001c692143d8140577323ec8033bfe868c44d79daa27cdd8a64913cf40"
metafile = true

[[files]]
file = "mods/hexical.pw.toml"
hash = "353bc9603d4bfa25ce7e2e15a1a8cf34f6ab18695cdafd8c4e0d351e841ac157"
metafile = true

[[files]]
file = "mods/hexpats.pw.toml"
hash = "c5acbe6f95e405cddd63b02845b406b86e8e1b0af65e85986f6d8cddc837fa40"
metafile = true

[[files]]
file = "mods/hexportation.pw.toml"
hash = "b5ed3b3b787b8cda46501f21bf1b7a1366a81a1ca64f87892e909eff19c15a56"
metafile = true

[[files]]
file = "mods/hexpose.pw.toml"
hash = "a3679744d85237d364e432d07acc54775ef0ab10c80c542c5d5fb5d683dc43d6"
metafile = true

[[files]]
file = "mods/hextended-staves.pw.toml"
hash = "f24bbafda4b129d94153f559f3f3612c6a96f167208f8e8f7c9d7a00237536e1"
metafile = true

[[files]]
file = "mods/hextweaks.pw.toml"
hash = "304fda9dadcfbc199dd2415aba2a164cb2f31fea6b44ed242271fef6fb194174"
metafile = true

[[files]]
file = "mods/hierophantics.pw.toml"
hash = "fe8b903b37f162385797a10af49859b2225980c1d8c1d335172bf5d6b44692c4"
metafile = true

[[files]]
file = "mods/incapacitated.pw.toml"
hash = "bf76c91bc8fdea48f9361c022f9d2535400ff38e4feff5b89e4f40e2b02637db"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inline.pw.toml"
hash = "77705ea58913cad0baa1964f8ba1a37b2fdf640b955a70f4bc1ad985cdd14a5f"
metafile = true

[[files]]
file = "mods/ioticblocks.pw.toml"
hash = "85412f19eccc9b4caa6932122e5e3c7b05aba22686b8cde137a96537d23ff322"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "f644c401c3ef437f661564171abc8be8f13ad71cb67461734ab402d2ebe7cc47"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "9495bb2388d7fa5ccf6b33b485f75c7ed15f8a59956406a92ad427e8504980e8"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "d6be91dc0a2aca23ee640818d8a8295c85ddb2db6e0413669ecac9600b01eef0"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "ead6f125d759a3bc5892416204319369836742556943d5fed6220dbdb8f32913"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lets-do-bakery.pw.toml"
hash = "6e4ef29d4f259f1b797dff8b02cf49eff8500ab4824412a3b49dd158f80f2947"
metafile = true

[[files]]
file = "mods/lets-do-bloomingnature.pw.toml"
hash = "621d313a03c38e6db7709406828c7f5212833757a044884dc8dfc37d1e9462f3"
metafile = true

[[files]]
file = "mods/lets-do-brewery.pw.toml"
hash = "f3f8fd71302e5303bd119379923fe88716cb182a781871bb9db1c25fb58ef6f8"
metafile = true

[[files]]
file = "mods/lets-do-camping.pw.toml"
hash = "036f6fe07477f6411ad855bf137ff8625fea6eca23ed4026d2c0fdb121d5b1d0"
metafile = true

[[files]]
file = "mods/lets-do-emi-compat.pw.toml"
hash = "81445c534ed0054a7f787b4cae2802a7bacbadf337298e2a89a30e86ed4e6fb8"
metafile = true

[[files]]
file = "mods/lets-do-herbalbrews.pw.toml"
hash = "f6275345ca358025bda3be46bcc29ac3f20ee04ec2e54d200a59ec96cb2630e5"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "419bd839d19392cc602591a1bd9975e02e4f946f93f161fa793865530628af63"
metafile = true

[[files]]
file = "mods/lets-do-wildernature.pw.toml"
hash = "c0fa611e6145c44263b04c5d0a308c6734eea192797beda2697880992a04967e"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "55167e582fd4841cd6c581beb53d341e94285c216e04b1d7bff0068e875be2a6"
metafile = true

[[files]]
file = "mods/loot-integrations.pw.toml"
hash = "2b8558c98a77d2aadd14be4ac745f38bbe941663922aaf8cd179fd6bcc003a5b"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "fde4be77cf20a4d2b2b82133c74b739b2a26b61de4e2ea15de978110873727d1"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "b573cf54b09dabe06138af1b3a8d925b51479623bcddf42d9ba4c99e4fa34f67"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "35c812e91d098b979ce4618ceee0ffc3adc3d857d234c99735977e0ac337d8bb"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "0f170663bb0f70d773ac5c3d24f09747253c5ba8a855b3a45fe7f1952e574b78"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "a6ffaf3b24a1312d3737417d70b20bb8b7c2d034851a24f672096380afe57dae"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "10640a16eb413ffdc56857e669230a0f8d05bf2cf17f1f5369bf5a56b2ce7f2d"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "4a7a7460f802eaf18bb298e31c4925a38e5e649ff11b08c61a5f88c03b886749"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "c0262f9744dd166ad1264c436f355be3c1ab170487db78b42b6ebabe64f84a24"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "cca59c22f3d72c86e6f33ab6497d7ce8a927aeff2517d7e4415602c623013bc3"
metafile = true

[[files]]
file = "mods/max-health-fix.pw.toml"
hash = "9b17fbb6ff79809ec9606b889cacda1d12ffd399d32b3b9f1c113b3de23c417a"
metafile = true

[[files]]
file = "mods/mermod.pw.toml"
hash = "ab35b9a0a8fc85070e93503cf93e393af424eebda3f892cc383ebb9ce188107a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0d438cc5a467aae6a9aa439a4547f990dfbaa4dc4e7bf5dbabf6d6e839411e83"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "3b72ceb1208f9b2215833d563d821c3493bcf0245770a595365e9c88fa93514f"
metafile = true

[[files]]
file = "mods/moreiotas.pw.toml"
hash = "6757363eeff33967a7beb9782d833cd9f23486933a88373e576a3856fbbaf1bd"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "3856d30860f36aa47470f113a724fd6bb440b182d24ec1ec365fc34f827704b3"
metafile = true

[[files]]
file = "mods/omnidirectional-movement.pw.toml"
hash = "9cad342d550b506879af2a8b42f3f24ce6b6012bc1bbcf29b11a095698700c68"
metafile = true

[[files]]
file = "mods/origins-extra-keybinds-fabric.pw.toml"
hash = "e65963729f01e0989b7a57ef340411fd0de3bc97c268e230e832dc69d2a07d64"
metafile = true

[[files]]
file = "mods/origins-umbrellas.pw.toml"
hash = "fc0f387194ab6c2ef47fb634bcea3f89e7b14253253472f448699d40c426b78e"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "faadbd329bd9b454d469c4ebdbcee1aa718b922c86ba68db8284152cb28ecf75"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/paucal.pw.toml"
hash = "49ef3ff0a74c6338f2160c4ee683ae34f745a38c0c87f2d7527e4f88406113fe"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "43b4a9ca9aaac5a16ed067aee92cafaf30d6166d62d7fa851179c6257ed75b59"
metafile = true

[[files]]
file = "mods/phlexiful.pw.toml"
hash = "6c12c8bf3a6b4ce0eff470be2941afead60953d23a09152d0e0c54c1bad4ed1f"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "7ad4ca488da13998ce660729167eef71ce1bdfb57ef1c5d593096fa459cec0f8"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "82c3a531c2180cd45f59e433315e31dc886c464a05ea38ea0b82ce1bc033c520"
metafile = true

[[files]]
file = "mods/scribble.pw.toml"
hash = "f4d3fd279c80231cfa832ad1fb58307849fbb6da495863005411d1c2606239e9"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/show-me-your-skin.pw.toml"
hash = "f29ba19cab72bdca9cbf01a557f5fb78513412094d4d4051295ab34ff1a86d9d"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "953bf8b7f1516c226bf80636b57941aa02557bc0a684d9c115440f52e46a8121"
metafile = true

[[files]]
file = "mods/simply-swords.pw.toml"
hash = "53756963029d3281ce1001a6129367541d2e092b34a4bb1cafeff77f3ec28902"
metafile = true

[[files]]
file = "mods/slate-works.pw.toml"
hash = "a7d049e908ae3a826176135b6bd753925451fb74fe3fdbd4ec3372ead38ab224"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/structure-essentials-forge-fabric.pw.toml"
hash = "a91400da1fd45c7c895c6b3289517cc85b53286cb00ea59b00e7489c7a4fb225"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "68586ae904f1cb0d0c914f8be6258c4d2a20e6b28cd0a07fc4940adba7dbc22f"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "7b7108d879e1e1c141b24d0d8fa268a6bbcd5c227875d156fcc62c3beec55f63"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/vics-point-blank.pw.toml"
hash = "26d8df12f49313a51be4862e9bb99ac199e5d985df2d41fa93c2dda88d3db2da"
metafile = true

[[files]]
file = "mods/villager-names-serilum.pw.toml"
hash = "a343e4dc55c01ae308ba84ba742e9acac817bd8b1b848e86b8c8a2cbfbdb3f27"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "838ef2f9506dc71d713098170b5c9434701bf8beb4e61b3a6efe90c56e1d8d12"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "f186401be01f7216a7bbd73c8e3e7cff96ab9db76d19029ee3be92f407b1b207"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "9d9ab7248c5a9ed01ce3e23fba5c60139065e31d94452e3179b263ac4be535aa"
metafile = true

[[files]]
file = "mods/yigd.pw.toml"
hash = "fc1d7a1ee1bb2d4906b2686d105c82b67297e8a8376bd3882fea0fdb7e6499eb"
metafile = true
